# Generated by Django 3.2.2 on 2021-05-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('brand', models.CharField(max_length=244)),
                ('description', models.CharField(max_length=244)),
                ('price', models.PositiveIntegerField()),
                ('sale', models.BooleanField()),
            ],
        ),
    ]
