# Generated by Django 3.2.2 on 2021-05-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('women', 'Women')], default='man', max_length=244),
        ),
    ]
