# Generated by Django 3.2.2 on 2021-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('man', 'Man'), ('women', 'Women')], default='clothing', max_length=244),
        ),
    ]
