# Generated by Django 3.2.2 on 2021-05-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, default=None, max_length=244, null=True),
        ),
    ]
