# Generated by Django 3.2.2 on 2021-05-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.URLField(default='https://image.emojipng.com/883/13277883.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.URLField(default='https://image.emojipng.com/883/13277883.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.URLField(default='https://image.emojipng.com/883/13277883.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.URLField(default='https://image.emojipng.com/883/13277883.jpg'),
        ),
    ]
