# Generated by Django 3.2.2 on 2021-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition1',
            field=models.CharField(blank=True, default=None, max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition2',
            field=models.CharField(blank=True, default=None, max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition3',
            field=models.CharField(blank=True, default=None, max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='designer_article',
            field=models.CharField(blank=True, default=None, max_length=244, null=True),
        ),
    ]
